'use client';
import {useState} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
export default function ContactForm({lang,products,connected,selected=''}){
const en=lang==='en';const [values,setValues]=useState({name:'',organization:'',email:'',phone:'',solution:selected,message:'',website:''});const [errors,setErrors]=useState({});const [state,setState]=useState('idle');const [message,setMessage]=useState('');
const names=en?{name:'Full name',organization:'Organization',email:'Email',phone:'Phone number',solution:'Solution of interest',message:'Tell us about your needs'}:{name:'Họ tên',organization:'Tổ chức/Đơn vị',email:'Email',phone:'Số điện thoại',solution:'Giải pháp quan tâm',message:'Nội dung nhu cầu'};
function change(k,v){setValues(x=>({...x,[k]:v}));setErrors(x=>({...x,[k]:''}));}
async function submit(e){e.preventDefault();const er={};if(!values.name.trim())er.name=en?'Please enter your name.':'Vui lòng nhập họ tên.';if(values.email&&!/^\S+@\S+\.\S+$/.test(values.email))er.email=en?'Enter a valid email.':'Email chưa hợp lệ.';if(values.phone&&!/^[+\d ()-]{8,20}$/.test(values.phone))er.phone=en?'Enter a valid phone number.':'Số điện thoại chưa hợp lệ.';if(!values.email&&!values.phone){er.email=en?'Provide an email or phone number.':'Cần email hoặc số điện thoại để phản hồi.';}setErrors(er);setMessage('');if(Object.keys(er).length)return;if(!connected){setState('offline');setMessage(en?'This form is not connected. No information has been sent or stored.':'Biểu mẫu chưa kết nối. Chưa có thông tin nào được gửi hoặc lưu.');return;}
setState('sending');try{const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,lang})});if(!res.ok){setState('error');setMessage(en?'Your request could not be delivered. Please try again later.':'Chưa thể chuyển yêu cầu tới nơi nhận. Vui lòng thử lại sau.');return;}setState('success');setMessage(en?'Your request has been received.':'Yêu cầu của bạn đã được tiếp nhận.');}catch{setState('error');setMessage(en?'Connection failed. Your information has not been sent.':'Lỗi kết nối. Thông tin của bạn chưa được gửi.');}}
return <form className="contact-form" onSubmit={submit} noValidate><h3>{en?'Start a conversation':'Chia sẻ nhu cầu của bạn'}</h3>{!connected&&<p className="form-notice">{en?'Preview form · Not connected to a recipient. Information is not sent or stored.':'Biểu mẫu xem thử · Chưa kết nối nơi nhận. Thông tin không được gửi hoặc lưu.'}</p>}<div className="form-grid">{['name','organization','email','phone'].map(k=><div className="field" key={k}><label htmlFor={'contact-'+k}>{names[k]}{k==='name'?' *':''}</label><input id={'contact-'+k} type={k==='email'?'email':k==='phone'?'tel':'text'} autoComplete={k==='organization'?'organization':k==='name'?'name':k==='phone'?'tel':'email'} value={values[k]} onChange={e=>change(k,e.target.value)} maxLength={200} aria-invalid={!!errors[k]} aria-describedby={errors[k]?'error-'+k:undefined} required={k==='name'}/>{errors[k]&&<span className="field-error" id={'error-'+k}>{errors[k]}</span>}</div>)}</div><div className="field"><label id="solution-label">{names.solution}</label><Select value={values.solution||'none'} onValueChange={v=>change('solution',v==='none'?'':v)}><SelectTrigger className="select-control" aria-labelledby="solution-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">{en?'Select a solution':'Chọn giải pháp'}</SelectItem>{products.map(p=><SelectItem key={p.id} value={p.id}>{p.data.title}</SelectItem>)}</SelectContent></Select></div><div className="field"><label htmlFor="contact-message">{names.message}</label><textarea id="contact-message" rows={4} value={values.message} maxLength={5000} onChange={e=>change('message',e.target.value)}/></div><div className="honeypot" aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={values.website} onChange={e=>change('website',e.target.value)}/></label></div><p className="form-help">{en?'* Name and a valid email or phone number are required.':'* Cần họ tên và email hoặc số điện thoại hợp lệ.'}</p><button className="button" type="submit" disabled={state==='sending'}>{state==='sending'?(en?'Sending…':'Đang gửi…'):connected?(en?'Send request':'Gửi yêu cầu'):(en?'Check information — not sent':'Kiểm tra thông tin — chưa gửi')}</button>{message&&<p role="status" className={'form-status '+state}>{message}</p>}</form>
}

