import Backdrop from './backdrop';
import {href} from '@/lib/routes.mjs';
import {sectionOrder,sectionAnchors} from '@/lib/sections.mjs';
import {ArrowUpRight,Database,Workflow,Monitor,GraduationCap} from 'lucide-react';
import AnalyticsBoundary from './section-analytics';
import CredentialViewer from './credential-viewer';
const ids=['data','operations','learning','education'];const icons=[Database,Workflow,Monitor,GraduationCap];
export function actionHref(action,records,lang){if(action.targetSectionId&&sectionAnchors[action.targetSectionId])return '/'+lang+'#'+sectionAnchors[action.targetSectionId];const doc=records.find(x=>x.id===action.targetContentId);return doc?href(doc,lang):null;}
export default function HomeSections({records,lang,preview=false}){
const en=lang==='en';const get=id=>records.find(x=>x.id===id);const photo=(d,priority=false)=><picture>{d.mobileImage&&<source media="(max-width: 700px)" srcSet={d.mobileImage}/>}<img src={d.image} alt={d.alt||''} width={priority?560:800} height={priority?620:600} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} style={{objectPosition:d.imageFocus||'50% 50%'}}/></picture>;
const media=(d,priority=false)=>d.image?<div className="section-photo">{photo(d,priority)}</div>:preview?<div className="media-pending">{en?'Real image pending — visible in preview only':'Chờ ảnh thật — chỉ hiển thị trong xem trước'}</div>:null;
const link=(a,i=0,event,productId)=>{const url=actionHref(a,records,lang);return url?<a key={i} className={'button '+(i?'outline':'')} href={url} data-event={event} data-product={productId||a.targetContentId||''}>{a.label}<ArrowUpRight size={18}/></a>:null;};
const intro=d=><div className="section-intro">{d.eyebrow&&<p className="eyebrow">{d.eyebrow}</p>}<h2>{d.title}</h2>{d.description&&<p className="lead">{d.description}</p>}</div>;
const pending=(id,d)=><section key={id} id={sectionAnchors[id]} className="container pending-module"><strong>{id} · {d?.title||id}</strong><p>{en?'Content pending approval — not visible publicly':'Nội dung chờ duyệt — không hiển thị công khai'}</p></section>;
const cards=(items,event)=><div className="cards">{items.map(x=><article className="content-card" key={x.id}>{x.data.image&&photo(x.data)}<div><h3>{x.data.title}</h3><p>{x.data.description}</p>{['project','news'].includes(x.kind)&&<a className="text-link" href={href(x,lang)} data-event={event} data-content={x.id}>{en?'Read more':'Xem chi tiết'}<ArrowUpRight size={18}/></a>}</div></article>)}</div>;
return <AnalyticsBoundary locale={lang}><div className="homepage-v2">{sectionOrder.map(id=>{const row=get(id);if(!row)return null;const d=row.data;if(!d.enabled)return preview?pending(id,d):null;
const attrs={id:sectionAnchors[id],'data-section':id};let content;
if(id==='H01')content=<section {...attrs} className={'brand-hero backdrop-host '+(!d.image&&!preview?'no-media':'')}><Backdrop data={d}/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">{d.eyebrow}</p><h1>{d.title}</h1><p className="lead">{d.description}</p><div className="actions">{d.actions?.map((a,i)=>link(a,i,i?'hero_contact_click':'hero_ecosystem_click'))}</div></div>{media(d,true)}</div></section>;
if(id==='H02')content=<section {...attrs} className="section context-section"><div className="container"><div className={"context-grid "+(!d.image&&!preview?"context-text-only":"")}><div className="context-copy">{intro(d)}<ol className="observations">{d.nodes?.map((n,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{n.title}</h3><p>{n.text}</p></div></li>)}</ol></div>{media(d)}</div><p className="section-bridge">{d.body}</p></div></section>;
if(id==='H03')content=<section {...attrs} className="section approach-section"><div className="container">{intro(d)}<ol className="capability-path">{d.nodes?.map((n,i)=><li key={i}><span className="path-dot" aria-hidden="true"/><h3>{n.title}</h3><strong>{n.label}</strong><p>{n.text}</p></li>)}</ol><p className="path-outcome">{d.outcome}</p><p className="section-bridge">{d.body}</p></div></section>;
if(id==='H04')content=<section {...attrs} className="section ecosystem-dark"><div className="container">{intro(d)}<div className="ecosystem-layers">{ids.map((groupId,i)=>{const g=get(groupId);if(!g)return null;const Icon=icons[i];return <article className="ecosystem-layer" key={groupId}><div className="layer-number"><Icon size={28}/><span>{String(i+1).padStart(2,'0')}</span></div><div><h3>{g.data.title}</h3><p>{g.data.valueProposition||g.data.description}</p></div><div className="layer-links">{records.filter(p=>p.kind==='product'&&p.data.groupId===groupId&&(groupId!=='learning'||p.id==='smart-study-2')).map(p=><a href={href(p,lang)} key={p.id} data-event={'ecosystem_layer_'+String(i+1).padStart(2,'0')+(p.id==='smart-ivier'?'_ivier':p.id==='ivihrm'?'_ivihrm':'')+'_click'} data-product={p.id}>{p.data.title}<ArrowUpRight size={18}/></a>)}{groupId==='learning'&&<a href={'/'+lang+'#moi-truong-hoc-tap-so'} data-event="ecosystem_layer_03_click">{d.classroomLabel}<ArrowUpRight size={18}/></a>}</div></article>})}</div><div className="actions">{d.actions?.map((a,i)=>link(a,i,'ecosystem_solutions_click'))}</div></div></section>;
if(id==='H05')content=<section {...attrs} className="section data-section"><div className="container data-grid"><div>{intro(d)}<div className="actions">{d.actions?.map((a,i)=>link(a,i,'digitization_detail_click'))}</div></div><div><ol className="records-path">{d.nodes?.map((n,i)=><li key={i}><span aria-hidden="true">{String(i+1).padStart(2,'0')}</span>{n.title}</li>)}</ol>{media(d)}</div></div></section>;
if(id==='H06')content=<section {...attrs} className="section operations-section"><div className="container">{intro(d)}<div className="solution-pair">{['smart-ivier','ivihrm'].map((pId,i)=>{const p=get(pId);return p&&<article key={p.id}><p className="eyebrow">{p.data.eyebrow}</p><h3>{p.data.title}</h3><p>{p.data.description}</p><ul>{p.data.highlights?.map((text,j)=><li key={j}>{text}</li>)}</ul>{p.data.supportNote&&<p className="support-note">{p.data.supportNote}</p>}{media(p.data)}{d.actions?.[i]&&link(d.actions[i],0,i?'ivihrm_detail_click':'smart_ivier_detail_click',pId)}</article>})}</div></div></section>;
if(id==='H07')content=<section {...attrs} className="section learning-section"><div className="container">{intro(d)}<div className="learning-connections">{d.nodes?.map((n,i)=><span key={i}>{n.title}</span>)}</div>{media(d)}<div className="learning-products">{['smart-study-2','interactive-displays','nexta'].map((pId,productIndex)=>{const p=get(pId);return p&&<article key={pId}><h3>{p.data.title}</h3><p>{p.data.description}</p>{media(p.data)}{d.actions?.[productIndex]&&link(d.actions[productIndex],0,'learning_solution_click',pId)}</article>})}</div><p className="section-bridge">{d.body}</p></div></section>;
if(id==='H08'){const p=get('ivivi');const method=d.method;const showMethod=method&&(preview||(method.status==='published'&&method.programScope?.trim()));content=<section {...attrs} className="section human-section"><div className="container">{intro(d)}<div className="ivivi-pillars">{p?.data.highlights?.map((text,i)=><div key={i}><GraduationCap size={26}/><h3>{text}</h3></div>)}</div><ol className="learning-path">{d.nodes?.map((n,i)=><li key={i}>{n.title}</li>)}</ol><h3 className="method-message">{d.body}</h3>{showMethod&&<div className="learning-method">{preview&&method.status!=='published'&&<p className="warning-box">{en?'Draft method — program scope pending':'Phương pháp đang nháp — chờ phạm vi chương trình'}</p>}<div className="method-bar"><span style={{flex:method.foundationPercent}}>{method.foundationPercent}%</span><span style={{flex:method.practicePercent}}>{method.practicePercent}%</span></div><p>{method.description}</p>{method.programScope&&<p>{method.programScope}</p>}</div>}{media(d)}<div className="actions">{d.actions?.map((a,i)=>link(a,i,'ivivi_detail_click'))}</div></div></section>;}
if(['H09','H10','H12','H12B'].includes(id)){const kind={H09:'project',H10:'partner',H12:'certificate',H12B:'news'}[id];const items=records.filter(x=>x.kind===kind&&(!preview||x.status==='published')).slice(0,id==='H10'?100:3);if(!items.length)return preview?pending(id,d):null;content=<section {...attrs} className="section"><div className="container">{intro(d)}{id==='H10'?<div className="logo-wall">{items.map(x=><article key={x.id}>{x.data.image&&photo(x.data)}<h3>{x.data.title}</h3><p>{x.data.category}</p><p>{x.data.description}</p>{x.data.ctaUrl&&<a href={x.data.ctaUrl} data-event="partner_detail_click" data-content={x.id}>{x.data.ctaLabel||x.data.title}</a>}</article>)}</div>:id==='H12'?<div className="cards">{items.map(x=><article className="content-card" key={x.id}><div><p>{x.data.category}</p><h3>{x.data.title}</h3><p>{x.data.description}</p>{x.data.documentUrl&&<CredentialViewer url={x.data.documentUrl} title={x.data.title} lang={lang} contentId={x.id}/>}</div></article>)}</div>:cards(items,id==='H09'?'case_study_click':'news_detail_click')}{id==='H12B'&&<a className="text-link" href={'/'+lang+'/'+(en?'news':'tin-tuc')}>{en?'All news':'Tất cả tin tức'}</a>}</div></section>;}
if(id==='H11'){if(!d.description&&!d.image&&!d.body)return preview?pending(id,d):null;content=<section {...attrs} className="section"><div className="container context-grid"><div>{intro(d)}<p>{d.body}</p><div className="actions">{d.actions?.map((a,i)=>link(a,i,'team_about_click'))}</div></div>{media(d)}</div></section>;}
if(id==='H13')content=<section {...attrs} className="section final-invitation"><div className="container">{intro(d)}<div className="actions">{d.actions?.map((a,i)=>link(a,i,'footer_contact_click'))}</div></div></section>;
return <div key={id}>{content}</div>;
})}</div></AnalyticsBoundary>;
}
