'use client';
import {useId} from 'react';
import {sectionOrder} from '@/lib/sections.mjs';
function Input({label,value,onChange,rows,type='text'}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{rows?<textarea id={id} rows={rows} value={value||''} onChange={e=>onChange(e.target.value)}/>:<input id={id} type={type} value={value??''} onChange={e=>onChange(type==='number'?Number(e.target.value):e.target.value)}/>}</div>}
export default function SectionEditor({doc,data,set,docs,lang,onMobileImage}){const required=['H01','H02','H03','H04','H13'].includes(doc.id);const pages=docs.filter(x=>!x.deleted&&['home','about','product','project','news','contact','index'].includes(x.kind));return <div className="section-settings"><h3>{doc.id} · Nội dung phân đoạn</h3><p className="form-help">Thứ tự H01–H13 và bốn lớp được cố định. Lưu và xuất bản độc lập theo ngôn ngữ.</p><label className="section-toggle"><input type="checkbox" checked={data.enabled!==false} disabled={required} onChange={e=>set('enabled',e.target.checked)}/> Hiển thị phân đoạn {required?'(phần nền tảng)':''}</label><Input label="Nhãn đầu phân đoạn" value={data.eyebrow} onChange={v=>set('eyebrow',v)}/><Input label="Câu nối / Thông điệp bổ sung" rows={3} value={data.body} onChange={v=>set('body',v)}/>{doc.id==='H03'&&<Input label="Kết quả hướng tới" value={data.outcome} onChange={v=>set('outcome',v)}/>} {doc.id==='H04'&&<Input label="Tên nhóm lớp học thông minh" value={data.classroomLabel} onChange={v=>set('classroomLabel',v)}/>}<Input label="Nguồn / Ghi chú biên tập (không công khai)" rows={3} value={data.source} onChange={v=>set('source',v)}/><button type="button" className="button outline small" onClick={onMobileImage}>Chọn ảnh riêng cho mobile</button>{data.mobileImage&&<><img src={data.mobileImage} width="160" height="120" alt="Ảnh mobile đang chọn"/><button type="button" className="text-link" onClick={()=>set('mobileImage','')}>Gỡ ảnh mobile</button></>}
{data.nodes?.map((n,i)=><div className="node-editor" key={i}><h4>Yếu tố {i+1}</h4><Input label={'Tên yếu tố '+(i+1)} value={n.title} onChange={v=>set('nodes',data.nodes.map((x,j)=>j===i?{...x,title:v}:x))}/>{doc.id==='H03'&&<Input label={'Nhãn yếu tố '+(i+1)} value={n.label} onChange={v=>set('nodes',data.nodes.map((x,j)=>j===i?{...x,label:v}:x))}/>} {['H02','H03'].includes(doc.id)&&<Input rows={3} label={'Mô tả yếu tố '+(i+1)} value={n.text} onChange={v=>set('nodes',data.nodes.map((x,j)=>j===i?{...x,text:v}:x))}/>}</div>)}
{!['H02','H03'].includes(doc.id)&&<><h3>Liên kết hành động</h3>{data.actions?.map((a,i)=><div className="node-editor" key={i}><Input label={'Nhãn liên kết '+(i+1)} value={a.label} onChange={v=>set('actions',data.actions.map((x,j)=>j===i?{...x,label:v}:x))}/><div className="field"><label htmlFor={doc.id+'-target-'+i}>Trang / Phân đoạn đích {i+1}</label><select id={doc.id+'-target-'+i} value={a.targetSectionId?'section:'+a.targetSectionId:'page:'+a.targetContentId} onChange={e=>{const [kind,id]=e.target.value.split(':');set('actions',data.actions.map((x,j)=>j===i?{label:x.label,...(kind==='section'?{targetSectionId:id}:{targetContentId:id})}:x))}}><optgroup label="Các trang hiện có">{pages.map(p=><option key={p.id} value={'page:'+p.id}>{p.translations[lang].draft.title||p.id}{p.translations[lang].status==='published'?'':' (chưa xuất bản)'}</option>)}</optgroup><optgroup label="Phân đoạn trang chủ">{sectionOrder.map(id=><option key={id} value={'section:'+id}>{id} · {docs.find(x=>x.id===id)?.translations[lang].draft.title}</option>)}</optgroup></select></div></div>)}</>}
{doc.id==='H08'&&data.method&&<div className="node-editor"><h3>Phương pháp học theo tỷ lệ</h3><p className="form-help">Nháp được xem trong preview. Chỉ công khai khi chọn Xuất bản, có phạm vi chương trình và xuất bản phân đoạn H08. Không phải tỷ lệ thành công.</p><div className="form-grid">{[['foundationPercent','Kiến thức nền (%)'],['practicePercent','Thực hành (%)']].map(([key,label])=><Input key={key} type="number" label={label} value={data.method[key]} onChange={v=>set('method',{...data.method,[key]:v})}/>)}</div><Input label="Phạm vi chương trình áp dụng" value={data.method.programScope} onChange={v=>set('method',{...data.method,programScope:v})}/><Input label="Mô tả phương pháp" rows={3} value={data.method.description} onChange={v=>set('method',{...data.method,description:v})}/><div className="field"><label htmlFor="method-status">Trạng thái module tỷ lệ</label><select id="method-status" value={data.method.status} onChange={e=>set('method',{...data.method,status:e.target.value})}><option value="draft">Nháp / Ẩn công khai</option><option value="published">Xuất bản (cần phạm vi)</option></select></div></div>}
</div>}
