'use client';
import {track} from './section-analytics';
import {useState} from 'react';
import {Menu, X,ChevronDown,Database,Workflow,Monitor,GraduationCap,ArrowUpRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTrigger,SheetClose,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {href,labels} from '@/lib/routes.mjs';
const icons={database:Database,workflow:Workflow,monitor:Monitor,graduation:GraduationCap};
export default function SiteHeader({lang,settings,groups,products,otherPath,home=false}){
const [open,setOpen]=useState(false);const t=labels[lang];const links=[{title:settings.navAbout,url:'/'+lang+'/'+(lang==='vi'?'gioi-thieu':'about')},{title:settings.navProjects,url:'/'+lang+'/'+(lang==='vi'?'khach-hang-du-an':'customers-projects')},{title:settings.navNews,url:'/'+lang+'/'+(lang==='vi'?'tin-tuc':'news')},{title:settings.navContact,url:'/'+lang+'/'+(lang==='vi'?'lien-he':'contact')}];
const groupItems=(g,menu)=>products.filter(p=>p.data.groupId===g.id).map(p=>menu?<DropdownMenuItem asChild key={p.id}><a className="mega-product" href={href(p,lang)}><span><strong>{p.data.title}</strong><small>{p.data.description}</small></span><ArrowUpRight size={17}/></a></DropdownMenuItem>:<a className="mobile-product" key={p.id} href={href(p,lang)}>{p.data.title}</a>);
return <><a className="skip-link" href="#main">{t.skip}</a><header className="header"><div className="container header-inner"><a className="brand" href={'/'+lang} aria-label={'iViTech — '+t.home}><img src={settings.logo} width="168" height="56" alt="iViTech"/></a><nav className="desktop-nav" aria-label={lang==='vi'?'Điều hướng chính':'Main navigation'}><DropdownMenu onOpenChange={v=>v&&track('header_ecosystem_open',{locale:lang,sectionId:'H01',action:'click'})}><DropdownMenuTrigger className="nav-trigger">{settings.navSolutions}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="mega-menu" align="center" sideOffset={24}><DropdownMenuItem asChild><a className="text-link" href={'/'+lang+'#he-sinh-thai'}>{settings.ecosystemOverview}</a></DropdownMenuItem><div className="mega-grid">{groups.map(g=>{const Icon=icons[g.data.icon]||Database;return <div key={g.id}><div className="mega-heading"><Icon size={25}/><h3>{g.data.title}</h3></div>{groupItems(g,true)}</div>})}</div></DropdownMenuContent></DropdownMenu><a href={links[1].url}>{links[1].title}</a><DropdownMenu><DropdownMenuTrigger className="nav-trigger">{settings.navResources}<ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent className="resources-menu" align="start" sideOffset={12}><DropdownMenuItem asChild><a href={links[2].url}>{links[2].title}</a></DropdownMenuItem></DropdownMenuContent></DropdownMenu><a href={links[3].url} onClick={()=>track('header_contact_click',{locale:lang,sectionId:'H01',action:'click'})}>{links[3].title}</a><a href={links[0].url}>{links[0].title}</a></nav><div className="header-actions"><a className="language-switch" href={otherPath} aria-label={t.language}><span className={lang==='vi'?'active':''}>VI</span><span aria-hidden="true">|</span><span className={lang==='en'?'active':''}>EN</span></a><Sheet open={open} onOpenChange={v=>{setOpen(v);if(v)track('mobile_menu_open',{locale:lang,sectionId:'H01',action:'click'})}}><SheetTrigger asChild><button className="icon-button mobile-toggle" aria-label={t.menu}><Menu size={24}/></button></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><div className="mobile-top"><SheetTitle>iViTech</SheetTitle><SheetClose asChild><button className="icon-button" aria-label={t.close}><X/></button></SheetClose></div><SheetDescription className="sr-only">{t.solutions}</SheetDescription><a href={'/'+lang}>{settings.navHome||t.home}</a><a href={'/'+lang+'#he-sinh-thai'} onClick={()=>setOpen(false)}>{settings.ecosystemOverview}</a><a href={links[0].url}>{links[0].title}</a><Accordion type="multiple">{groups.map(g=><AccordionItem value={g.id} key={g.id}><AccordionTrigger>{g.data.title}</AccordionTrigger><AccordionContent>{groupItems(g,false)}</AccordionContent></AccordionItem>)}</Accordion>{links.slice(1).map(a=><a key={a.url} href={a.url}>{a.title}</a>)}<a className="button" href={links[3].url}>{settings.ctaLabel}</a></SheetContent></Sheet></div></div></header></>
}

