 'use client';
import {useEffect,useState} from 'react';
const statuses={unread:'Chưa đọc',partial:'Đã đọc một phần',read:'Đã đọc',inaccessible:'Chưa truy cập được',missing_link:'Thiếu liên kết'};
export default function SourceLibrary({api}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api('sources').then(setRows).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const field=(key,label,rows=2)=><label className="field" key={key}>{label}<textarea rows={rows} value={selected[key]||''} onChange={e=>setSelected({...selected,[key]:e.target.value})}/></label>;
 return <section className="admin-panel"><h2>Tài liệu nguồn — nội bộ</h2><p>Chỉ quản trị viên truy cập. Tên danh mục không xác nhận tính năng, dự án hay quyền công bố tài sản. Nguồn trùng URL được giữ tên gốc để truy vết.</p>{error&&<p role="alert" className="error-box">{error}</p>}
 <div className="source-list">{rows.map(r=><button className="source-row" key={r.sourceId} onClick={()=>{setSelected(r);setError('')}}><strong>{r.sourceId} · {r.originalTitle}</strong><span>{statuses[r.readStatus]}</span></button>)}</div>
 {selected&&<div className="section-settings"><h3>{selected.sourceId} · {selected.originalTitle}</h3><p>Dòng CSV {selected.csvLine} · {selected.group} · STT {selected.originalRow?.STT||'Không có'}</p>{selected.originalUrl&&<a className="text-link" href={selected.originalUrl} target="_blank" rel="noreferrer">Mở tài liệu gốc</a>}<p>{selected.originalSummary||'Không có tóm tắt gốc.'}</p>{!!selected.aliases?.length&&<p>Tên khác cùng URL: {selected.aliases.join('; ')}</p>}<details><summary>Các cột CSV gốc</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(selected.originalRow,null,2)}</pre></details>
 <div className="form-grid"><label className="field">Trạng thái đọc<select className="select-control" value={selected.readStatus} onChange={e=>setSelected({...selected,readStatus:e.target.value})}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field">Phạm vi sử dụng<select className="select-control" value={selected.scope} onChange={e=>setSelected({...selected,scope:e.target.value})}><option value="editorial">Nguồn biên tập</option><option value="internal">Nội bộ</option><option value="public_asset">Tài sản được chọn công khai</option></select></label>{field('resolvedUrl','URL sau khi mở')}{field('canonicalDocumentId','Mã tài liệu chuẩn')}{field('documentType','Loại tài liệu đã xác định')}{field('sourceDate','Ngày / phiên bản ghi trong nguồn')}</div>{field('findings','Nội dung đã đọc và vị trí trích dẫn',5)}{field('notes','Trang liên quan / mâu thuẫn / trở ngại',4)}<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('sources/'+selected.sourceId,'PUT',{version:selected.version,data:selected});setSelected(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>Lưu thông tin nguồn</button></div>}
 </section>;
}
