import {groups,products,home} from './seed.mjs';
const bi=(vi,en)=>({vi,en});
const extra={
digitization:{audience:bi('Cơ quan, tổ chức và doanh nghiệp cần tổ chức lại hồ sơ, dữ liệu.','Public-sector organizations and businesses that need to organize their records and data.'),body:bi('Số hóa không bắt đầu từ máy quét. Số hóa bắt đầu từ cách hồ sơ được tổ chức. Khi hồ sơ phân tán hoặc khó tra cứu, giá trị tri thức bị giới hạn.','Digitization starts with how records are organized. When records are fragmented or difficult to retrieve, their value as knowledge is limited.'),blocks:[
bi(['Chỉnh lý và chuẩn hóa','Phân loại, sắp xếp và tổ chức hồ sơ theo yêu cầu quản lý.'],['Organization & standardization','Classify, arrange and organize records for management needs.']),
bi(['Số hóa và tạo lập dữ liệu','Chuyển đổi tài liệu thành nguồn dữ liệu số thuận tiện cho quản lý.'],['Digitization & data creation','Convert documents into digital data to support management.']),
bi(['Tìm kiếm, truy xuất và bảo quản','Hỗ trợ tiếp cận hồ sơ nhanh hơn và bảo toàn giá trị thông tin.'],['Search, retrieval & preservation','Support easier access to records and preserve their informational value.']),
bi(['Nền tảng cho tri thức và AI','Tạo tiền đề để dữ liệu phục vụ công việc, điều hành và ứng dụng AI.'],['A foundation for knowledge & AI','Lay the groundwork for data to support work, operations and AI applications.'])]},
'smart-ivier':{audience:bi('Cán bộ và các bộ phận chuyên môn tại phường, xã.','Officials and specialist departments at ward and commune level.'),body:bi('Smart iVier tổ chức dữ liệu và tri thức công vụ thành nền tảng dùng chung: đúng nguồn, đúng quyền và có thể tái sử dụng. AI hỗ trợ; cán bộ kiểm tra trước khi sử dụng kết quả. Smart iVier không thay thế hệ thống chính thức hoặc trách nhiệm của cán bộ.','Smart iVier organizes public-service data and knowledge into a shared foundation with appropriate sources, permissions and reuse. AI assists; officials review outputs before use. Smart iVier does not replace official systems or officials’ responsibilities.'),blocks:[
bi(['Trợ lý Công vụ','Hỗ trợ cán bộ xử lý nhiệm vụ và khai thác tri thức công vụ.'],['Public-service assistant','Support officials in handling tasks and using public-service knowledge.']),
bi(['Trợ lý Pháp luật','Hỗ trợ tìm căn cứ phục vụ công việc của cán bộ.'],['Legal assistant','Support officials in finding relevant references for their work.']),
bi(['Trợ lý Soạn thảo văn bản','Hỗ trợ soạn thảo kết quả từ dữ liệu và tri thức công vụ.'],['Document drafting assistant','Support drafting based on public-service data and knowledge.'])]},
ivihrm:{audience:bi('Doanh nghiệp và bộ phận quản lý nhân sự.','Businesses and human resources teams.'),body:bi('Quản lý tập trung, chuẩn hóa nghiệp vụ và từng bước ứng dụng AI trong vận hành nhân sự. Các ứng dụng AI hỗ trợ người dùng, được trình bày riêng với nghiệp vụ HRM cơ bản.','Centralize HR management, standardize processes and gradually apply AI to HR operations. AI applications support users and are distinguished from core HRM processes.'),blocks:[
bi(['Hệ thống HRM cơ bản','Hồ sơ nhân viên; chấm công và phân ca; lương, thưởng và phúc lợi; hợp đồng và giấy tờ.'],['Core HRM','Employee records; time and shift tracking; pay, rewards and benefits; contracts and documents.']),
bi(['Ứng dụng AI hỗ trợ','OCR và mô hình ngôn ngữ; trợ lý nhân sự ảo; hỗ trợ trích xuất dữ liệu và phân tích hồ sơ.'],['AI-assisted applications','OCR and language models; virtual HR assistance; support for data extraction and record analysis.'])]},
'smart-study-2':{audience:bi('Học sinh và nhà trường.','Students and schools.'),body:bi('Smart Study 2 là máy tính bảng học tập dành cho học sinh, trong nhóm giải pháp kết nối thiết bị, nội dung và con người. iViTech giữ vai trò đại lý phân phối được nêu trong hồ sơ. Thông số chi tiết đang chờ bổ sung.','Smart Study 2 is a learning tablet for students, offered within solutions connecting devices, content and people. iViTech acts as a distributor as described in the profile. Detailed specifications are pending.'),blocks:[bi(['Thiết bị cho học tập','Máy tính bảng học tập dành cho học sinh.'],['A device for learning','A learning tablet for students.'])]},
'interactive-displays':{audience:bi('Nhà trường và môi trường lớp học.','Schools and classroom learning environments.'),body:bi('Màn hình tương tác hỗ trợ trình chiếu trực quan và tương tác liền mạch trong học tập. iViTech giữ vai trò đại lý phân phối được nêu trong hồ sơ. Cấu hình và thông số sản phẩm đang chờ bổ sung.','Interactive displays support visual presentation and seamless interaction in learning. iViTech acts as a distributor as described in the profile. Product configurations and specifications are pending.'),blocks:[bi(['Trình chiếu và tương tác','Kết nối thiết bị với không gian học tập.'],['Presentation & interaction','Connect devices with the learning environment.'])]},
nexta:{audience:bi('Nhà trường, học sinh và gia đình.','Schools, students and families.'),body:bi('Ứng dụng Nexta cung cấp học liệu số, hỗ trợ kết nối học tập giữa trường và nhà. iViTech là đại lý phân phối; Nexta không được giới thiệu là sản phẩm do iViTech tự phát triển. Nội dung chi tiết đang chờ bổ sung.','The Nexta app offers digital learning resources to help connect learning at school and at home. iViTech is a distributor; Nexta is not presented as an iViTech-developed product. Further details are pending.'),blocks:[bi(['Kết nối học tập','Thiết bị, học liệu và con người cùng tạo nên môi trường học tập số.'],['Connected learning','Devices, learning resources and people together form a digital learning environment.'])]},
ivivi:{audience:bi('Người học, học sinh và nhà trường.','Learners, students and schools.'),body:bi('iViVi đồng hành cùng người học phát triển ngoại ngữ, năng lực số, tư duy phản biện và khả năng ứng dụng AI an toàn, có trách nhiệm. Học thông minh – Tư duy thông minh – Sống thông minh.','iViVi supports learners in developing language skills, digital competence, critical thinking and the safe, responsible use of AI. Learn smart – Think smart – Live smart.'),blocks:[
bi(['Ngoại ngữ và hội nhập','Phát triển năng lực giao tiếp, sử dụng ngoại ngữ trong học tập và từng bước mở rộng khả năng hội nhập.'],['Languages & global engagement','Develop communication and language skills for learning and gradually broaden opportunities for global engagement.']),
bi(['Công dân số và năng lực số','Sử dụng công nghệ an toàn, có trách nhiệm; hình thành tư duy phản biện và kỹ năng thích ứng trong môi trường số.'],['Digital citizenship & competence','Use technology safely and responsibly; develop critical thinking and adaptability in digital environments.']),
bi(['Trí tuệ nhân tạo và Robotics','Khám phá AI, lập trình, robot và các hoạt động sáng tạo gắn với thực tiễn.'],['AI & robotics','Explore AI, programming, robotics and creative activities connected to real-world practice.'])]}
};
export function initialRecords(){
const out=[];const add=(id,kind,l,data,sort=0,groupId='')=>out.push({id,kind,lang:l,data,sort,groupId});
for(const l of ['vi','en']){
groups.forEach((g,i)=>add(g.id,'group',l,{title:g.name[l],description:g.description[l],icon:g.icon,slug:g.id,source:'PDF 6; brief 5'},i));
products.forEach((p,i)=>{const x=extra[p.id];add(p.id,'product',l,{title:p.name[l],slug:p.slug[l],description:p.description[l],body:x.body[l],audience:x.audience[l],blocks:x.blocks.map(b=>({title:b[l][0],text:b[l][1]})),source:p.source,seoTitle:p.name[l]+' | iViTech',seoDescription:p.description[l],image:'',alt:'',ctaLabel:home.cta[l],ctaUrl:'',groupId:p.group},i,p.group)});
add('home','home',l,{title:home.title[l],accent:l==='vi'?'năng lực số':'digital capability',description:home.description[l],eyebrow:home.eyebrow[l],ctaLabel:home.cta[l],ctaUrl:'#contact',secondaryLabel:home.explore[l],secondaryUrl:'#ecosystem',image:'/brand/hero-glass.webp',alt:'',seoTitle:home.title[l]+' | iViTech',seoDescription:home.description[l],modules:[
{type:'hero',title:home.title[l],enabled:true},
{type:'recognition',title:l==='vi'?'Ghi nhận':'Recognition',enabled:false},
{type:'solutions',title:home.ecosystem[l],enabled:true},
{type:'consult',title:home.consult[l],text:home.consultText[l],enabled:true},
{type:'project',title:l==='vi'?'Khách hàng & Dự án':'Customers & Projects',enabled:false},
{type:'testimonial',title:l==='vi'?'Phản hồi khách hàng':'Customer feedback',enabled:false},
{type:'partner',title:l==='vi'?'Đối tác đồng hành':'Our partners',enabled:false},
{type:'certificate',title:l==='vi'?'Năng lực & Ghi nhận':'Capabilities & Recognition',enabled:false},
{type:'news',title:l==='vi'?'Tin tức từ iViTech':'News from iViTech',enabled:true},
{type:'contact',title:l==='vi'?'Kết nối với iViTech':'Connect with iViTech',enabled:true}
]});
add('about','about',l,{title:l==='vi'?'Công nghệ chỉ có ý nghĩa khi tạo ra giá trị thực':'Technology matters when it creates real value',slug:l==='vi'?'gioi-thieu':'about',eyebrow:l==='vi'?'Câu chuyện iViTech':'The iViTech story',description:home.description[l],body:l==='vi'?'iViTech ra đời để thu hẹp khoảng cách giữa công nghệ được trang bị và năng lực thực sự được tạo ra. Tri thức chỉ phát huy sức mạnh khi được tổ chức, kết nối và chuyển hóa thành công cụ phục vụ con người.':'iViTech was created to narrow the gap between technology provided and capability actually developed. Knowledge becomes powerful when it is organized, connected and transformed into tools that serve people.',blocks:[
{title:l==='vi'?'Bắt đầu từ năng lực cần tạo ra':'Start with the capability to be built',text:l==='vi'?'Tổ chức dữ liệu và tri thức; đưa phần mềm, AI vào đúng công việc; kết nối thiết bị và môi trường số; phát triển nội dung phù hợp; triển khai, đào tạo, vận hành và cải tiến trong thực tế.':'Organize data and knowledge; apply software and AI to the right tasks; connect devices and digital environments; develop appropriate content; deploy, train, operate and improve in practice.'},
{title:l==='vi'?'Một hệ sinh thái, một hành trình năng lực số':'One ecosystem, one journey of digital capability',text:l==='vi'?'Từ nền tảng dữ liệu số, vận hành số và môi trường học tập số đến giáo dục và năng lực của con người.':'From digital data foundations, operations and learning environments to education and human capability.'},
{title:l==='vi'?'Được dẫn dắt bởi kinh nghiệm thực tiễn':'Guided by practical experience',text:l==='vi'?'Đội ngũ kết hợp kinh nghiệm trong quản trị, công nghệ, giáo dục, tổ chức triển khai và phát triển thị trường. Lãnh đạo trực tiếp tham gia phát triển sản phẩm và đồng hành trong quá trình triển khai.':'The team combines experience in management, technology, education, implementation and market development. Leaders participate directly in product development and support implementation.'}
],source:'PDF 2, 4–6, 17',image:'',alt:''});
add('site','settings',l,{title:'iViTech',logo:'/brand/ivitech-primary.png',description:home.description[l],ctaLabel:home.cta[l],footerText:l==='vi'?'Biến tri thức thành năng lực số.':'Turning knowledge into digital capability.',copyright:'© iViTech',email:'',phone:'',address:'',facebook:'',youtube:'',zalo:'',navAbout:l==='vi'?'Giới thiệu':'About',navSolutions:l==='vi'?'Sản phẩm & Giải pháp':'Products & Solutions',navProjects:l==='vi'?'Khách hàng/Dự án':'Customers/Projects',navNews:l==='vi'?'Tin tức':'News',navContact:l==='vi'?'Liên hệ':'Contact'});
add('contact','contact',l,{title:l==='vi'?'Cùng nhau kiến tạo những giá trị bền vững':'Creating lasting value together',description:l==='vi'?'iViTech chào đón các cơ quan, tổ chức, doanh nghiệp, nhà trường và chuyên gia cùng hợp tác phát triển, ứng dụng công nghệ và kiến tạo giải pháp thiết thực.':'iViTech welcomes public-sector organizations, businesses, schools and experts to collaborate on technology applications and practical solutions.',body:l==='vi'?'Chia sẻ nhu cầu của tổ chức bạn để bắt đầu cuộc trao đổi.':'Share your organization’s needs to start a conversation.',slug:l==='vi'?'lien-he':'contact'});
for(const k of ['project','news']) add(k+'-index','index',l,{title:k==='project'?(l==='vi'?'Khách hàng & Dự án':'Customers & Projects'):(l==='vi'?'Tin tức':'News'),description:l==='vi'?'Nội dung đang được cập nhật.':'Content is being updated.',collection:k,slug:k==='project'?(l==='vi'?'khach-hang-du-an':'customers-projects'):(l==='vi'?'tin-tuc':'news')});
}return out;
}

