const pair=(vi,en)=>({vi,en});
export const groups=[
{id:'data',name:pair('Nền tảng dữ liệu số','Digital data foundation'),description:pair('Tổ chức hồ sơ, dữ liệu và tri thức làm nền tảng cho khai thác số.','Organize records, data and knowledge as a foundation for digital use.'),icon:'database'},
{id:'operations',name:pair('Nền tảng vận hành số','Digital operations'),description:pair('Đưa AI, dữ liệu và phần mềm vào hoạt động điều hành, quản trị.','Bring AI, data and software into day-to-day operations and management.'),icon:'workflow'},
{id:'learning',name:pair('Môi trường học tập số','Digital learning environments'),description:pair('Kết nối thiết bị, nội dung và không gian học tập hiện đại.','Connect devices, content and modern learning spaces.'),icon:'monitor'},
{id:'education',name:pair('Giáo dục và năng lực số','Education & digital capability'),description:pair('Phát triển ngoại ngữ, năng lực số, AI và tư duy công nghệ.','Develop language skills, digital competence, AI and technological thinking.'),icon:'graduation'}];
export const products=[
{id:'digitization',group:'data',slug:pair('so-hoa-ho-so','records-digitization'),name:pair('Chỉnh lý và số hóa hồ sơ','Records organization & digitization'),description:pair('Tổ chức, chuẩn hóa và số hóa hồ sơ để thuận tiện cho quản lý, tìm kiếm và khai thác tri thức.','Organize, standardize and digitize records to support management, retrieval and knowledge use.'),source:'PDF 7–8'},
{id:'smart-ivier',group:'operations',slug:pair('smart-ivier','smart-ivier'),name:pair('Smart iVier','Smart iVier'),description:pair('Kết nối dữ liệu và tri thức công vụ, hỗ trợ cán bộ xử lý nhiệm vụ với ba trợ lý chuyên năng.','Connect public-service data and knowledge to support officials in their work through three specialized assistants.'),source:'PDF 9–10'},
{id:'ivihrm',group:'operations',slug:pair('ivihrm','ivihrm'),name:pair('iViHRM','iViHRM'),description:pair('Quản lý dữ liệu và nghiệp vụ nhân sự tập trung, từng bước ứng dụng AI để hỗ trợ vận hành.','Centralize HR data and processes, with a gradual approach to using AI to support operations.'),source:'PDF 11'},
{id:'smart-study-2',group:'learning',slug:pair('smart-study-2','smart-study-2'),name:pair('Smart Study 2','Smart Study 2'),description:pair('Máy tính bảng học tập dành cho học sinh, thuộc nhóm giải pháp môi trường học tập số.','A learning tablet for students, offered as part of the digital learning environment solutions.'),source:'PDF 12'},
{id:'interactive-displays',group:'learning',slug:pair('man-hinh-tuong-tac','interactive-displays'),name:pair('Màn hình tương tác','Interactive displays'),description:pair('Hỗ trợ trình chiếu trực quan và tương tác trong môi trường học tập.','Support visual presentation and interaction in learning environments.'),source:'PDF 12'},
{id:'nexta',group:'learning',slug:pair('ung-dung-nexta','nexta-app'),name:pair('Ứng dụng Nexta','Nexta app'),description:pair('Học liệu số hỗ trợ kết nối hoạt động học tập giữa trường và nhà.','Digital learning resources that help connect learning at school and at home.'),source:'PDF 12; brief 5, 15'},
{id:'ivivi',group:'education',slug:pair('ivivi','ivivi'),name:pair('iViVi','iViVi'),description:pair('Phát triển ngoại ngữ, năng lực số và tư duy công nghệ thông qua AI, Robotics và các hoạt động học tập.','Develop language skills, digital competence and technological thinking through AI, robotics and learning activities.'),source:'PDF 13–14'}];
export const home={title:pair('Biến tri thức thành năng lực số','Turning knowledge into digital capability'),eyebrow:pair('Hệ sinh thái AI • Chuyển đổi số • Giáo dục công nghệ','AI ecosystem • Digital transformation • Technology education'),description:pair('iViTech kết nối dữ liệu, AI, phần mềm và giáo dục công nghệ để hỗ trợ cơ quan, doanh nghiệp và nhà trường xây dựng năng lực số từ thực tiễn.','iViTech connects data, AI, software and technology education to help public-sector organizations, businesses and schools build digital capability through practical application.'),ecosystem:pair('Hệ sinh thái giải pháp iViTech','The iViTech solution ecosystem'),cta:pair('Nhận tư vấn','Request a consultation'),explore:pair('Khám phá giải pháp','Explore solutions'),consult:pair('Cùng xây dựng giải pháp phù hợp với tổ chức của bạn','Let’s shape the right solution for your organization'),consultText:pair('Bắt đầu từ nhu cầu thực tế. Kết nối công nghệ với năng lực cần tạo ra.','Start with real needs. Connect technology with the capability you want to build.')};

