import {sectionOrder} from './sections.mjs';
const pair=(vi,en)=>({vi,en});
const rows=(vi,en)=>pair(vi.map(([title,text='',label=''])=>({title,text,label})),en.map(([title,text='',label=''])=>({title,text,label})));
const entries=[
['H01',pair('Kiến tạo năng lực số từ tri thức và công nghệ.','Building digital capability through knowledge and technology.'),pair('iViTech kết nối dữ liệu, tri thức, phần mềm, AI, thiết bị và giáo dục để giúp tổ chức và con người khai thác công nghệ hiệu quả hơn, hình thành năng lực số và tạo ra giá trị thực.','iViTech connects data, knowledge, software, AI, devices and education to help organizations and people use technology more effectively, build digital capability and create practical value.'),{eyebrow:pair('Hệ sinh thái AI · Chuyển đổi số · Giáo dục công nghệ','AI ecosystem · Digital transformation · Technology education'),actions:pair([{label:'Khám phá hệ sinh thái',targetSectionId:'H04'},{label:'Trao đổi cùng iViTech',targetContentId:'contact'}],[{label:'Explore our ecosystem',targetSectionId:'H04'},{label:'Talk to iViTech',targetContentId:'contact'}])}],
['H02',pair('Khi tri thức chưa trở thành năng lực số','When knowledge has yet to become digital capability'),pair('Mỗi cơ quan, doanh nghiệp và trường học đều sở hữu tri thức có giá trị trong hồ sơ, dữ liệu, quy trình, kinh nghiệm và con người. Giá trị ấy cần được khai thác thông qua cách tổ chức dữ liệu, ứng dụng công nghệ và hỗ trợ con người trong công việc, quản trị, học tập và sáng tạo.','Every public-sector organization, business and school holds valuable knowledge in its records, data, processes, experience and people. Realizing that value requires organized data, appropriate technology and support for people in their work, management, learning and creativity.'),{eyebrow:pair('Câu chuyện iViTech','The iViTech story'),body:pair('iViTech hướng tới thu hẹp khoảng cách giữa công nghệ được trang bị và năng lực thực sự được hình thành.','iViTech aims to narrow the gap between having technology and developing the capability to use it.'),nodes:rows([
['Có dữ liệu, nhưng chưa dễ khai thác','Hồ sơ và dữ liệu nằm ở nhiều nguồn có thể khiến việc tìm kiếm, truy xuất, tổng hợp và kế thừa tri thức chưa thuận lợi.'],['Có công nghệ, nhưng chưa luôn đi vào đúng việc','Phần mềm, AI và thiết bị tạo giá trị khi được đưa vào đúng tác vụ, quy trình và môi trường sử dụng.'],['Có công cụ, nhưng chưa thành năng lực chung','Hiệu quả dễ dừng ở từng cá nhân khi dữ liệu, tri thức và cách sử dụng chưa được tổ chức để chia sẻ và kế thừa.'],['Có thiết bị, nhưng chưa đủ để tạo năng lực','Môi trường học tập số cần kết nối thiết bị, nội dung, phần mềm, phương pháp và con người.']],
[['Data exists, but can be difficult to use','Records and data spread across different sources can make finding, retrieving, combining and reusing knowledge difficult.'],['Technology exists, but does not always fit the task','Software, AI and devices create value when applied to suitable tasks, processes and environments.'],['Tools exist, but capability remains individual','Benefits can remain isolated when data, knowledge and ways of working are not organized for sharing and reuse.'],['Devices alone do not build capability','Digital learning environments need to connect devices, content, software, methods and people.']])}],
['H03',pair('Không bắt đầu từ công nghệ. Bắt đầu từ năng lực cần tạo ra.','Start with the capability to build, then the technology to enable it.'),pair('iViTech tiếp cận chuyển đổi số từ năng lực cần hình thành trong công việc, quản trị và học tập. Dữ liệu, công nghệ, môi trường sử dụng, nội dung và hoạt động triển khai cần được kết nối để hỗ trợ con người ứng dụng hiệu quả trong thực tế.','iViTech approaches digital transformation through the capabilities needed in work, management and learning. Data, technology, the use environment, content and implementation need to connect so people can apply them effectively in practice.'),{eyebrow:pair('Con đường iViTech','The iViTech approach'),outcome:pair('Năng lực số → Giá trị thực','Digital capability → Practical value'),body:pair('Khi các yếu tố này được kết nối, những giải pháp cùng hình thành một hệ sinh thái hướng tới năng lực số.','Connecting these elements brings solutions together in an ecosystem focused on digital capability.'),nodes:rows([
['Dữ liệu và tri thức','Hồ sơ và dữ liệu được tổ chức để tìm kiếm, truy xuất, sử dụng và kế thừa tri thức.','Tổ chức để có thể khai thác'],['Phần mềm và AI','Hỗ trợ đúng tác vụ, quy trình, vai trò và trong phạm vi con người kiểm soát.','Đưa công nghệ vào đúng công việc'],['Thiết bị và môi trường số','Thiết bị phát huy giá trị khi gắn với nền tảng, nội dung và môi trường phù hợp.','Kết nối với bối cảnh sử dụng'],['Nội dung và phương pháp','Giúp người học sử dụng kiến thức, thực hành và sáng tạo với công nghệ.','Học qua thực hành và ứng dụng'],['Triển khai và đồng hành','Đồng hành để giải pháp được sử dụng, thích ứng với thực tế và phát huy giá trị.','Đưa giải pháp vào thực tế']],
[['Data and knowledge','Organize records and data so knowledge can be found, retrieved, used and passed on.','Organized for use'],['Software and AI','Support suitable tasks, processes and roles under human control.','Technology for the task'],['Devices and digital environments','Connect devices with appropriate platforms, content and environments.','Connected to the context'],['Content and methods','Help learners apply knowledge, practice and create with technology.','Learning through practice'],['Implementation and ongoing support','Help solutions become part of real work, adapt to the context and deliver value.','From solutions to practice']])}],
['H04',pair('Một hệ sinh thái. Bốn lớp giá trị. Một mục tiêu.','One ecosystem. Four layers of value. One shared goal.'),pair('Hệ sinh thái iViTech kết nối dữ liệu, công nghệ, môi trường số và con người. Mỗi lớp giải quyết một nhu cầu riêng, cùng hướng tới việc hình thành năng lực số và tạo ra giá trị thực.','The iViTech ecosystem connects data, technology, digital environments and people. Each layer addresses a distinct need, with a shared goal of building digital capability and creating practical value.'),{eyebrow:pair('Hệ sinh thái iViTech','The iViTech ecosystem'),classroomLabel:pair('Giải pháp lớp học thông minh','Smart classroom solutions'),actions:pair([{label:'Xem các giải pháp',targetSectionId:'H05'}],[{label:'View the solutions',targetSectionId:'H05'}])}],
['H05',pair('Từ kho hồ sơ đến nền dữ liệu có thể khai thác','From stored records to usable digital data'),pair('Tổ chức, chuẩn hóa và số hóa hồ sơ để hỗ trợ quản lý, tìm kiếm, truy xuất và khai thác tri thức.','Organize, standardize and digitize records to support management, search, retrieval and knowledge use.'),{eyebrow:pair('Nền tảng dữ liệu số','Digital data foundation'),nodes:rows(['Hồ sơ','Chỉnh lý','Số hóa','Dữ liệu','Truy xuất','Tri thức'].map(x=>[x]),['Records','Organization','Digitization','Data','Retrieval','Knowledge'].map(x=>[x])),actions:pair([{label:'Tìm hiểu chỉnh lý và số hóa',targetContentId:'digitization'}],[{label:'Explore records digitization',targetContentId:'digitization'}])}],
['H06',pair('Đưa dữ liệu và AI vào công việc thực tế','Bringing data and AI into everyday work'),pair('Hai giải pháp cho nhu cầu công vụ và quản trị nhân sự, cùng hướng tới năng lực vận hành số.','Two solutions for public-service work and HR management, both supporting digital operations.'),{eyebrow:pair('Nền tảng vận hành số','Digital operations foundation'),actions:pair([{label:'Khám phá Smart iVier',targetContentId:'smart-ivier'},{label:'Khám phá iViHRM',targetContentId:'ivihrm'}],[{label:'Explore Smart iVier',targetContentId:'smart-ivier'},{label:'Explore iViHRM',targetContentId:'ivihrm'}])}],
['H07',pair('Kiến tạo môi trường học tập số','Creating digital learning environments'),pair('Kết nối thiết bị, nội dung, phần mềm, phương pháp và con người để công nghệ hỗ trợ việc dạy và học.','Connect devices, content, software, methods and people so technology can support teaching and learning.'),{eyebrow:pair('Môi trường học tập số','Digital learning environment'),nodes:rows(['Thiết bị','Nội dung','Phần mềm','Phương pháp','Con người'].map(x=>[x]),['Devices','Content','Software','Methods','People'].map(x=>[x])),body:pair('iViTech phân phối các giải pháp học tập theo vai trò được nêu trong hồ sơ.','iViTech distributes learning solutions in the role described in its company profile.'),actions:pair([{label:'Tìm hiểu sản phẩm',targetContentId:'smart-study-2'},{label:'Tìm hiểu sản phẩm',targetContentId:'interactive-displays'},{label:'Tìm hiểu ứng dụng',targetContentId:'nexta'}],[{label:'Explore the product',targetContentId:'smart-study-2'},{label:'Explore the product',targetContentId:'interactive-displays'},{label:'Explore the app',targetContentId:'nexta'}])}],
['H08',pair('Từ sự tò mò đến năng lực làm chủ công nghệ','From curiosity to the ability to use technology with confidence'),pair('iViVi kết hợp nội dung, công nghệ và hoạt động thực hành để người học phát triển ngoại ngữ, năng lực số, tư duy và khả năng ứng dụng AI.','iViVi combines content, technology and practical activities to develop language skills, digital competence, thinking and the ability to apply AI.'),{eyebrow:pair('Năng lực số con người','Human digital capability'),body:pair('Chú trọng thực hành, trải nghiệm và ứng dụng','An emphasis on practice, experience and application'),nodes:rows(['Hiểu','Thực hành','Ứng dụng','Sáng tạo','Năng lực'].map(x=>[x]),['Understand','Practice','Apply','Create','Build capability'].map(x=>[x])),method:pair({foundationPercent:20,practicePercent:80,programScope:'',description:'20% kiến thức nền; 80% thực hành – trải nghiệm – ứng dụng.',status:'draft'},{foundationPercent:20,practicePercent:80,programScope:'',description:'20% foundational knowledge; 80% practice, experience and application.',status:'draft'}),actions:pair([{label:'Khám phá iViVi',targetContentId:'ivivi'}],[{label:'Explore iViVi',targetContentId:'ivivi'}])}],
['H09',pair('Giá trị được hình thành trong thực tiễn','Value created through practical application'),pair('',''),{source:pair('Word: Phú Lâm (Smart iVier), Trường Tiểu học Trương Công Định (giáo dục) chỉ là ứng viên; chưa có hồ sơ và quyền công bố.','Word: Phú Lâm (Smart iVier) and Trương Công Định Primary School (education) are editorial candidates only; publication evidence and permission are pending.')}],
['H10',pair('Khách hàng và đối tác','Customers and partners'),pair('',''),{}],
['H11',pair('Đồng hành bằng kinh nghiệm thực tiễn','Working alongside you with practical experience'),pair('',''),{actions:pair([{label:'Về iViTech',targetContentId:'about'}],[{label:'About iViTech',targetContentId:'about'}])}],
['H12',pair('Nền tảng cho sự hợp tác lâu dài','A foundation for long-term collaboration'),pair('',''),{}],
['H12B',pair('Tin tức từ iViTech','News from iViTech'),pair('',''),{}],
['H13',pair('Cùng iViTech biến tri thức và công nghệ thành năng lực số.','Turn knowledge and technology into digital capability with iViTech.'),pair('Chia sẻ nhu cầu của tổ chức để cùng xác định hướng tiếp cận và giải pháp phù hợp.','Share your organization’s needs so we can explore a suitable approach and solution together.'),{actions:pair([{label:'Trao đổi cùng iViTech',targetContentId:'contact'}],[{label:'Talk to iViTech',targetContentId:'contact'}])}]
];
export function supplementRecords(){return entries.flatMap(([id,title,description,extra])=>['vi','en'].map(lang=>({id,lang,sort:sectionOrder.indexOf(id),data:{title:title[lang],description:description[lang],enabled:!['H09','H10','H11','H12','H12B'].includes(id),nodes:[],actions:[],image:'',alt:'',source:'Script bổ sung H01–H13, mục '+(sectionOrder.indexOf(id)+5),...Object.fromEntries(Object.entries(extra).map(([k,v])=>[k,v[lang]]))}})));}
export function migrateSupplement(db){if(db.prepare("SELECT value FROM meta WHERE key='supplement-v2'").get())return;
const time=new Date().toISOString();db.exec('BEGIN IMMEDIATE');try{
for(const r of supplementRecords()){db.prepare("INSERT INTO documents(id,kind,sort,created) VALUES(?,'section',?,?) ON CONFLICT(id) DO NOTHING").run(r.id,r.sort,time);const draft=JSON.stringify(r.data);const publish=!['H09','H10','H11','H12','H12B'].includes(r.id);db.prepare('INSERT OR IGNORE INTO translations(document_id,lang,draft,published,status,updated,published_at) VALUES(?,?,?,?,?,?,?)').run(r.id,r.lang,draft,publish?draft:null,publish?'published':'draft',time,publish?time:null);}
function patch(id,lang,changes){const t=db.prepare('SELECT * FROM translations WHERE document_id=? AND lang=?').get(id,lang);if(!t)return;db.prepare('INSERT INTO revisions(document_id,lang,data,action,actor,created) VALUES(?,?,?,?,?,?)').run(id,lang,t.draft,'before-supplement','migration',time);const apply=j=>j?JSON.stringify({...JSON.parse(j),...changes}):null;db.prepare('UPDATE translations SET draft=?,published=?,version=version+1,updated=? WHERE document_id=? AND lang=?').run(apply(t.draft),apply(t.published),time,id,lang);}
for(const lang of ['vi','en']){const en=lang==='en';patch('site',lang,{navSolutions:en?'Ecosystem':'Hệ sinh thái',ctaLabel:en?'Talk to iViTech':'Trao đổi cùng iViTech',navHome:en?'Home':'Trang chủ',ecosystemOverview:en?'Ecosystem overview':'Tổng quan hệ sinh thái'});patch('education',lang,{title:en?'Human digital capability':'Năng lực số con người'});
const values=en?['From records to digital data assets','From data and knowledge to operational and management capability','From devices to a connected learning environment','From learning knowledge to building capability']:['Từ hồ sơ đến tài sản dữ liệu số','Từ dữ liệu và tri thức đến năng lực vận hành, quản trị','Từ thiết bị đến môi trường học tập được kết nối','Từ học kiến thức đến hình thành năng lực'];['data','operations','learning','education'].forEach((id,i)=>patch(id,lang,{valueProposition:values[i]}));
patch('smart-ivier',lang,{eyebrow:en?'AI support for public-service work':'Giải pháp AI hỗ trợ công vụ',heroHeadline:en?'One knowledge foundation. Three specialized assistants.':'Một nền tri thức. Ba trợ lý chuyên năng.',description:en?'A shared knowledge foundation that helps officials use data, handle tasks and draft public-service outputs.':'Nền tri thức dùng chung hỗ trợ cán bộ khai thác dữ liệu, xử lý nhiệm vụ và soạn thảo kết quả công vụ.',body:en?'Smart iVier connects public-service data and knowledge to help officials find information, handle tasks and draft outputs within a controlled workflow.\n\nData and knowledge are organized for reuse. AI provides assistance; officials verify and remain responsible for using the results. Smart iVier does not replace official systems.':'Smart iVier kết nối dữ liệu và tri thức công vụ để hỗ trợ cán bộ tìm thông tin, xử lý nhiệm vụ và soạn thảo kết quả trong phạm vi được kiểm soát.\n\nDữ liệu và tri thức được tổ chức để có thể khai thác, sử dụng lại. AI hỗ trợ, cán bộ kiểm tra và chịu trách nhiệm sử dụng kết quả. Smart iVier không thay thế hệ thống chính thức.',ctaLabel:en?'Discuss Smart iVier':'Trao đổi về Smart iVier',highlights:en?['Public-service assistant','Legal assistant','Document drafting assistant']:['Trợ lý Công vụ','Trợ lý Pháp luật','Trợ lý Soạn thảo văn bản'],supportNote:en?'AI assists; officials review and use the results.':'AI hỗ trợ; cán bộ kiểm tra và sử dụng kết quả.'});
patch('ivihrm',lang,{highlights:en?['Employee records','Attendance and shift scheduling','Payroll, rewards and benefits','Contracts and documents']:['Hồ sơ nhân viên','Chấm công và phân ca','Lương thưởng và phúc lợi','Hợp đồng và giấy tờ']});
patch('ivivi',lang,{highlights:en?['Languages and global integration','Digital citizenship and digital competence','AI and Robotics']:['Ngoại ngữ và hội nhập','Công dân số và năng lực số','AI và Robotics']});
const smart=db.prepare('SELECT draft FROM translations WHERE document_id=? AND lang=?').get('smart-ivier',lang);const blocks=JSON.parse(smart.draft).blocks||[];patch('smart-ivier',lang,{blocks:[...blocks,...(en?[{title:'Needs and suitable uses',text:'Find information and supporting references across sources, summarize data and prepare drafts. These are suitable use scenarios based on the profile, not demonstrations of independently tested features.'},{title:'Intended value',text:'Reduce repetitive work, retain reusable knowledge and support service quality. Outcomes are qualitative, with no measured performance claim.'},{title:'Principles for use',text:'Appropriate sources and permissions, verification and governance. AI supports officials; it does not replace their responsibilities or official systems.'}]:[{title:'Nhu cầu và tình huống sử dụng',text:'Tìm thông tin và căn cứ từ nhiều nguồn, hỗ trợ tổng hợp dữ liệu, dự thảo và xử lý nhiệm vụ. Đây là tình huống phù hợp với mô tả hồ sơ, không phải demo tính năng đã kiểm thử.'},{title:'Giá trị hướng tới',text:'Giảm áp lực thao tác, giữ lại và tái sử dụng tri thức, hỗ trợ chất lượng phục vụ. Diễn đạt định tính, không gắn số đo hiệu quả chưa có nguồn.'},{title:'Nguyên tắc sử dụng',text:'Đúng nguồn, đúng quyền, có kiểm chứng và có quản trị. AI hỗ trợ; cán bộ kiểm tra và chịu trách nhiệm. Không thay thế hệ thống chính thức.'}])]});
}
db.prepare("INSERT INTO meta(key,value) VALUES('supplement-v2','1')").run();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
